baseURL = "https://docs.shokoanime.com/"
DefaultContentLanguage = "en"
title = "Shoko Docs"
enableGitInfo = true

disableKinds = ["taxonomyTerm"]

[outputs]
	home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
	unsafe= true

[languages]
	[languages.en]
		contentDir = "content/en"
		title = "Shoko"
		languageName = "English"
		weight = 1

[params]
	images = ["icon.png"]